### ISSUE TITLE
AttributeError: module 'diffvg' has no attribute 'FilterType'

### ISSUE THREAD

**Issue by chikiuso** [pschaldenbrand/StyleCLIPDraw#3]
Hi, thanks for your sharing the project, idea and code. I tried to run the colab and it stop at the pydiffvg import , showing the following error : 

AttributeError: module 'diffvg' has no attribute 'FilterType'

I tried to google and install the diffvg GitHub manually but still no luck, do you have any idea I could make it work? thanks for your help!

**Comment by pschaldenbrand** [comment]
Hi @chikiuso Please restart your notebook (Runtime -> restart runtime) after running the "Pre installation" cell.  I'm now noticing that the instructions at the top of the notebook are slightly outdated, so I will update them today, but please refer to them.  Thanks!

**Comment by chikiuso** [comment]
thanks a lot!

**Comment by chikiuso** [comment]
Hi @pschaldenbrand , sorry to disturb you again, I faced the following error after passing the import , the screenshot attached as follows :

[https://ibb.co/S51kjF4](url)

**Comment by pschaldenbrand** [comment]
No trouble, @chikiuso 

Unfortunately, I cannot see the error in the screenshot you sent.  Could you please click the "4 frames" button and take another screenshot, or just attach the text for the full error message? Thanks

The error does look similar to Issue #2 .  Please see if that may fix the issue.
