### ISSUE TITLE
cpu inference colab

### ISSUE THREAD

**Issue by AK391** [pschaldenbrand/StyleCLIPDraw#4]
is inference possible on cpu in colab?

**Comment by pschaldenbrand** [comment]
It's possible, though, I think it may be prohibitively slow without the GPU acceleration.

I'm trying it right now.  I needed to change a line from  `device = torch.device('cuda')` to `device = torch.device('cpu')`. It has been running for 10 minutes and hasn't finished a single iteration of optimization. I'll leave it running, but at this rate it would take days to produce one image :(

**Comment by AK391** [comment]
@pschaldenbrand ok thanks for checking
