### ISSUE TITLE
Error on colab

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pschaldenbrand/StyleCLIPDraw#8]
Hey guys,

Thank you for sharing the code :) I am trying to use it in colab but after the installation cell is done I got the following error:

```
AttributeError: module 'diffvg' has no attribute 'FilterType'
```

**Comment by pschaldenbrand** [comment]
Hi @FrancescoSaverioZuppichini , you must restart the notebook after running the installation cell. In the top menu: Runtime -> Restart Runtime
